### PR TITLE
Simplify dependencies

### PR DESCRIPTION
**Pull request by saraedum**
no need for run dependencies since all the host dependencies have run_exports.

### CODE REVIEW

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender.

**Comment by saraedum** [comment]
@isuruf, any clue what this might be all about?

```
{standard input}: Assembler messages:

{standard input}:393613: Warning: end of file not at end of a line; newline inserted

{standard input}:394274: Error: unknown pseudo-op: `.lbb57222'

{standard input}: Error: open CFI at the end of file; missing .cfi_endproc directive

aarch64-conda-linux-gnu-c++: fatal error: Killed signal terminated program cc1plus
```

**Comment by isuruf** [comment]
Out of memory. Try cross compiling for aarch64 too

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Pull request merged**
